import { StyleSheet } from '@react-pdf/renderer';

export const colors = {
  void: '#0A0A0F',
  ink: '#0E0C22',
  violet: '#5B4FE8',
  lavender: '#8B6FE8',
  gold: '#E8A020',
  white: '#FFFFFF',
  body: '#6A6A8A',
  muted: '#4A4A6A',
  border: '#1A1A2A',
  red: '#ef4444',
  green: '#22c55e',
};

export const styles = StyleSheet.create({
  page: { backgroundColor: colors.void, padding: 40, fontFamily: 'Helvetica' },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 30,
    paddingBottom: 20,
    borderBottom: `1 solid ${colors.border}`,
  },
  logo: { fontSize: 24, fontWeight: 'bold', color: colors.gold, letterSpacing: 4 },
  reportTitle: { fontSize: 20, fontWeight: 'bold', color: colors.white, marginBottom: 4 },
  reportSubtitle: { fontSize: 10, color: colors.body },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: colors.lavender,
    textTransform: 'uppercase',
    letterSpacing: 2,
    marginBottom: 8,
    marginTop: 20,
  },
  table: { width: '100%', marginTop: 8 },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: colors.ink,
    padding: 8,
    borderRadius: 4,
  },
  tableHeaderCell: {
    fontSize: 8,
    fontWeight: 'bold',
    color: colors.lavender,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  tableRow: {
    flexDirection: 'row',
    padding: 8,
    borderBottom: `0.5 solid ${colors.border}`,
  },
  tableRowAlt: {
    flexDirection: 'row',
    padding: 8,
    backgroundColor: 'rgba(255,255,255,0.02)',
    borderBottom: `0.5 solid ${colors.border}`,
  },
  tableCell: { fontSize: 9, color: colors.body },
  tableCellWhite: { fontSize: 9, color: colors.white },
  summaryCard: {
    backgroundColor: colors.ink,
    padding: 16,
    borderRadius: 8,
    border: `1 solid ${colors.border}`,
    marginBottom: 8,
  },
  summaryLabel: {
    fontSize: 8,
    color: colors.lavender,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 4,
  },
  summaryValue: { fontSize: 18, fontWeight: 'bold', color: colors.white },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTop: `0.5 solid ${colors.border}`,
    paddingTop: 10,
  },
  footerText: { fontSize: 8, color: colors.muted },
  badge: { padding: '2 6', borderRadius: 4, fontSize: 8 },
  badgePaid: { backgroundColor: 'rgba(91,79,232,0.2)', color: colors.lavender },
  badgeOverdue: { backgroundColor: 'rgba(239,68,68,0.2)', color: colors.red },
  badgeDue: { backgroundColor: 'rgba(232,160,32,0.2)', color: colors.gold },
});
